import React from "react";
import Link from "next/link";
import { ShieldCheck, FileText, ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service - InviteOly",
  description: "Terms and conditions governing the use of the InviteOly event management platform.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0F0F0F] text-white pt-24 pb-20 font-work-sans">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
        {/* Back Link */}
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-xs text-neutral-400 hover:text-[#B89047] transition-colors mb-8"
        >
          <ArrowLeft className="size-3.5" /> Back to Home
        </Link>

        {/* Header */}
        <div className="border-b border-neutral-800 pb-8 mb-10">
          <span className="text-xs font-semibold tracking-[0.2em] text-[#B89047] uppercase font-space-grotesk">
            LEGAL AGREEMENT
          </span>
          <h1 className="text-3xl sm:text-5xl font-bold font-space-grotesk text-white mt-2 tracking-tight">
            Terms of Service
          </h1>
          <p className="text-xs sm:text-sm text-neutral-400 mt-2">
            Last Updated: January 1, 2026 · Effective Date: January 1, 2026
          </p>
        </div>

        {/* Content Body */}
        <div className="prose prose-invert max-w-none text-neutral-300 text-sm sm:text-base leading-relaxed space-y-8">
          <section className="bg-neutral-900/40 border border-neutral-800/80 rounded-2xl p-6 sm:p-8 space-y-4">
            <h2 className="text-xl font-bold font-space-grotesk text-white flex items-center gap-2.5">
              <FileText className="size-5 text-[#B89047]" />
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using the InviteOly platform (&quot;InviteOly&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;), including our website, mobile scanning applications, partner directory, and QR code generation tools, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold font-space-grotesk text-white">
              2. Description of Services
            </h2>
            <p>
              InviteOly provides event hosts, venues, and authorized partners with modern guest management, digital RSVP tracking, personalized cryptographic QR ticketing, and entry gate scanning verification tools. Our service does not guarantee guest attendance but provides the verifiable digital infrastructure to orchestrate invitation access.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold font-space-grotesk text-white">
              3. Host Accounts & Responsibilities
            </h2>
            <p>
              Event Hosts agree to provide accurate event, venue, and guest information. Hosts are solely responsible for ensuring that all invitations issued through the platform comply with local regulations and event capacity limits. Hosts must keep account credentials, OTP verification codes, and scanning API tokens strictly confidential.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold font-space-grotesk text-white">
              4. QR Tickets & Single-Entry Validity
            </h2>
            <p>
              Each ticket generated by InviteOly contains a unique cryptographic identifier. Once scanned and verified via our scanner app, the ticket is flagged as &quot;Checked In&quot; and cannot be reused by another attendee unless explicitly configured as a multi-entry pass by the Host.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold font-space-grotesk text-white">
              5. Partner & Venue Network Terms
            </h2>
            <p>
              Partners (such as venues, catering services, photographers, and planners) listed in our directory agree to honor stated availability, space capacities, and referral arrangements. InviteOly reserves the right to suspend or remove any partner that misrepresents venue amenities or violates quality standards.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold font-space-grotesk text-white">
              6. Payments, Invoicing & Refunds
            </h2>
            <p>
              Package fees are billed according to the selected tier (Intimate, Signature, Grand, or Enterprise Custom). Invoices issued through our admin system must be settled according to stated terms via Stripe, approved credit card, or verified bank transfer. Refunds for completed software ticket deployments are governed by our event cancellation policy.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold font-space-grotesk text-white">
              7. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, InviteOly and its affiliates shall not be liable for indirect, incidental, or consequential damages, including loss of venue reservations or event delays caused by internet disruptions beyond our reasonable control.
            </p>
          </section>

          <section className="bg-neutral-900/40 border border-neutral-800/80 rounded-2xl p-6 sm:p-8 space-y-2">
            <h2 className="text-xl font-bold font-space-grotesk text-white flex items-center gap-2.5">
              <ShieldCheck className="size-5 text-[#B89047]" />
              8. Contact Legal Support
            </h2>
            <p className="text-sm text-neutral-400">
              For questions regarding our Terms of Service or to report violations, please contact our legal counsel at{" "}
              <a href="mailto:legal@InviteOly.com" className="text-[#B89047] hover:underline font-medium">
                legal@InviteOly.com
              </a>{" "}
              or via our{" "}
              <Link href="/contact" className="text-[#B89047] hover:underline font-medium">
                Contact Page
              </Link>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}

